### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by Lihis** [xKippi/gnome-shell-extension-sane-airplane-mode#10]
The extension porting guide for GNOME Shell 46 has been published: https://gjs.guide/extensions/upgrading/gnome-shell-46.html. At the time of writing this issue it is in a state where it might get updated still.

**Comment by AntiKippi** [comment]
Yeah I've already seen this, does not seem like those changes are going to break the extension. However the earliest I gonna have a look at this is when GNOME 46 is available on my Arch machine.

**Comment by AntiKippi** [comment]
Test succeed and I have no issues just adding the new shell version. Closing this as fixed by [b2feeb3](https://github.com/AntiKippi/gnome-shell-extension-sane-airplane-mode/commit/b2feeb375834acd2ad2c7b9be2af18adba843d13)
